services:
  - type: web
    name: r2-image-uploader
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: R2_ACCESS_KEY
        value: cfc713ffa3be56083bbc6f8d22a2049b
      - key: R2_SECRET_KEY
        value: 66750be844b26284232ffa0fddc3291304edbb3244aef9dc561550bf8d0d2f8c
      - key: R2_ACCOUNT_ID
        value: 306d68c3c11511ad63a6a509f1f22cbd
      - key: R2_BUCKET
        value: stick-ios-image
